### ISSUE TITLE
启动报错了。。。但不知道怎么解决（依赖都装全了）ubuntu 16.04

### ISSUE THREAD

**Issue by lgs3137** [grapeot/WechatForwardBot#3]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from ActivityInfo import ActivityInfo
  File "/opt/WechatForwardBot/ActivityInfo.py", line 8, in <module>
    import matplotlib.pyplot as pp
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 37, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_axes.py", line 24, in <module>
    import matplotlib.dates as _  # <-registers a date unit converter
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/dates.py", line 125, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/usr/local/lib/python3.5/dist-packages/dateutil/rrule.py", line 55
    raise ValueError, "Can't create weekday with n == 0"
                    ^
SyntaxError: invalid syntax

**Comment by lgs3137** [comment]
sudo pip3 install python-dateutil --upgrade
完美解决了~
