### ISSUE TITLE
为什么老抛 列表索引超出范围 呢？

### ISSUE THREAD

**Issue by lgs3137** [grapeot/WechatForwardBot#4]
2017-06-19 17:19:29,758 : INFO : adding document #0 to Dictionary(0 unique tokens: [])
2017-06-19 17:19:29,759 : INFO : built Dictionary(14 unique tokens: ['aa', 'pengni', 'dfjkdng', 'aaa', 'activity']...) from 1 documents (total 51 corpus positions)
2017-06-19 17:19:29,759 : INFO : collecting document frequencies
2017-06-19 17:19:29,759 : INFO : PROGRESS: processing document #0
2017-06-19 17:19:29,759 : INFO : calculating IDF weights for 1 documents and 13 features (14 matrix non-zeros)
2017-06-19 17:19:29,768 : ERROR : We need at least 1 word to plot a word cloud, got 0.
2017-06-19 17:19:29,768 : ERROR : list index out of range
2017-06-19 17:19:29,770 : ERROR : list index out of range
2017-06-19 17:19:32,750 : ERROR : list index out of range
2017-06-19 17:19:36,537 : ERROR : list index out of range
2017-06-19 17:19:41,558 : ERROR : list index out of range
2017-06-19 17:19:45,972 : ERROR : list index out of range
2017-06-19 17:19:50,583 : ERROR : list index out of range
2017-06-19 17:20:09,645 : INFO : Generating activity info for 狗儿.
2017-06-19 17:20:10,504 : INFO : Sending activity file activityInfo/1497864009648-4685.png to @@7aaf75bce76a97b49f6e4212d09551b325f8205448b973a873ccba259778976a.
2017-06-19 17:20:11,220 : ERROR : list index out of range
2017-06-19 17:20:35,347 : ERROR : list index out of range
2017-06-19 17:20:41,360 : ERROR : list index out of range

**Comment by grapeot** [comment]
应该是这个原因：`ERROR : We need at least 1 word to plot a word cloud, got 0.`

在群里说几句话应该就好了~

**Comment by lgs3137** [comment]
不是的，就是群员每说一句话就抛一次这个错误。。。

**Comment by lgs3137** [comment]
对了，我main.py里开了斗图模式后就卡这里了。。。(是不是因为主目录没有featuresall.txt导致的？还有就是HistoryImages有部分图片，但是执行DoutuRobot/dedupAndCopy.sh貌似不能转换成jpg生成jpgs目录)
[log.txt](https://github.com/grapeot/WechatForwardBot/files/1086828/log.txt)

I0620 10:17:45.229037  7646 net.cpp:200] relu2 does not need backward computation.
I0620 10:17:45.229044  7646 net.cpp:200] conv2 does not need backward computation.
I0620 10:17:45.229051  7646 net.cpp:200] norm1 does not need backward computation.
I0620 10:17:45.229059  7646 net.cpp:200] pool1 does not need backward computation.
I0620 10:17:45.229066  7646 net.cpp:200] relu1 does not need backward computation.
I0620 10:17:45.229074  7646 net.cpp:200] conv1 does not need backward computation.
I0620 10:17:45.229136  7646 net.cpp:200] data does not need backward computation.
I0620 10:17:45.229159  7646 net.cpp:242] This network produces output prob
I0620 10:17:45.229194  7646 net.cpp:255] Network initialization done.
I0620 10:17:45.770469  7646 upgrade_proto.cpp:44] Attempting to upgrade input file specified using deprecated transformation parameters: /root/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0620 10:17:45.770537  7646 upgrade_proto.cpp:47] Successfully upgraded file specified using deprecated data transformation parameters.
W0620 10:17:45.770547  7646 upgrade_proto.cpp:49] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0620 10:17:45.770555  7646 upgrade_proto.cpp:53] Attempting to upgrade input file specified using deprecated V1LayerParameter: /root/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0620 10:17:46.342845  7646 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
I0620 10:17:46.438140  7646 net.cpp:744] Ignoring source layer loss
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    DoutuProcessor('./DoutuFeatures.txt')  # Uncomment to enable Dou Tu
  File "/opt/WechatForwardBot/DoutuProcessor.py", line 29, in __init__
    self.imageSearcher = ImageSearcher(doutuFeatureFn)
  File "/opt/WechatForwardBot/ImageSearcher.py", line 35, in __init__
    self.parseFeature(featurefn)
  File "/opt/WechatForwardBot/ImageSearcher.py", line 60, in parseFeature
    imgfn, hash, imgfeatures = line.split('\t')
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by lgs3137** [comment]
大神建个群吧，大家有问题可以讨论讨论~

**Comment by grapeot** [comment]
如果是这样的话，感觉每次造tag cloud的函数都被调用了一次。。这个比较奇怪。。要不跟踪debug看一下？

**Comment by grapeot** [comment]
关于斗图的那个问题，我开了个新issue哈。https://github.com/grapeot/WechatForwardBot/issues/5

**Comment by grapeot** [comment]
如果还是一直抛的话，感觉要自己debug一下了。。我没有遇到过这样的情况。。

**Comment by lgs3137** [comment]
main.py里面
# #Some global switches for debugging use only
isDebug = True

这个配置？？？

**Comment by grapeot** [comment]
不是呢~ 我的意思是跟进去就用正常的debug技巧看一下~ 不是特定的一个开关~ 虽然这个开关如果打开的话会打出来很多log也会有助于debug。

**Comment by lgs3137** [comment]
能打包一份你的鸭哥demo目录上来么？参考下...
